name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  SKIP_DEPLOYMENT: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run eslint
        id: lint-check
        if: always()

      - name: Build
        run: npm run build
        id: build-check
        if: always()

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Test
        run: npm run test
        id: test-check
        if: always()

      - name: Run Playwright tests
        run: npm run test:e2e
        id: test-e2e-check
        if: always()

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Trigger deployment
        if: github.ref == 'refs/heads/main' && env.SKIP_DEPLOYMENT == 'false'
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main' && env.SKIP_DEPLOYMENT == 'false'
        run: |
          echo "Deploying to Render"
          git push https://github.com/lemon1964/full-stack-open-pokedex.git HEAD:main

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main' && env.SKIP_DEPLOYMENT == 'false'
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          WITH_V: true
